services:
  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
      - "5095:8080"  # HTTP port mapping
      - "7100:8081"  # HTTPS port mapping
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ConnectionStrings__DefaultConnection=Server=sql1,1433;Database=CurrencyDB;User Id=sa;Password=Password1;TrustServerCertificate=True;
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro
    depends_on:
      - sql1
    networks:
      - app_network

  sql1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1
    ports:
      - "1401:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  sqldata:
    driver: local